# PersistentVolume statico con hostPath (sul nodo dove gira il pod)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""          # importante: vuoto per hostPath statico
  hostPath:
    path: "/mnt/jenkins_home"   # <-- cartella che creerai tu
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""          # deve essere vuoto
  resources:
    requests:
      storage: 50Gi
  volumeName: jenkins-pv        # binding statico al PV sopra
